#服务器端口号
server:
  port: 80

#目前是什么环境 dev 或 prod
spring:
  profiles:
    active: prod

  thymeleaf:
    cache: false # 禁用模板引擎的 缓存
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

#mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml  #指定全局配置文件的位置
  mapper-locations: classpath:mybatis/mapper/*.xml       #指定sql映射文件的位置

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql



